services:
  - type: web
    name: flask-restaurant-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_CLUSTER
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
